## Append samples you want in your CSV to this file as resources ##
resources:
- keycloak_v1alpha1_keycloak.yaml
- keycloak_v1alpha1_keycloakrealm.yaml
- keycloak_v1alpha1_keycloakclient.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
